project:
  type: website
  resources:
    - files/*
    - images/*
    - headshot.jpg

website:
  title: "Sara Scribner"
  page-footer:
    center: "Sara Scribner  ·  2026"
  navbar:
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: _fun.html
    toc: false
    smooth-scroll: true
